import pandas as pd
from faker import Faker
import random

fake = Faker()

# Number of rows to generate (adjust this to achieve the desired file size)
num_rows = 1000000  # Start with a smaller number and increase as needed

# Create a list to store the data
data = []
for _ in range(num_rows):
    row = {
        "BilledCost": fake.pydecimal(left_digits=5, right_digits=2, positive=True),
        "BillingAccountId": fake.uuid4(),
        "BillingAccountName": fake.company(),
        "BillingAccountType": random.choice(["Enterprise", "Pay-As-You-Go"]),
        "BillingCurrency": "USD",
        "BillingPeriodEnd": fake.date_between(start_date="-1y", end_date="today"),
        "BillingPeriodStart": fake.date_between(start_date="-2y", end_date="-1y"),
        "ChargeCategory": random.choice(["Compute", "Storage", "Networking"]),
        "ChargeClass": random.choice(["Standard", "Premium"]),
        "ChargeDescription": fake.sentence(nb_words=6),
        "ChargeFrequency": random.choice(["Monthly", "Hourly"]),
        "ChargePeriodEnd": fake.date_between(start_date="-1y", end_date="today"),
        "ChargePeriodStart": fake.date_between(start_date="-2y", end_date="-1y"),
        "CommitmentDiscountCategory": random.choice(["None", "Reserved Instance"]),
        "CommitmentDiscountId": fake.uuid4(),
        "CommitmentDiscountName": fake.word(),
        "CommitmentDiscountStatus": random.choice(["Active", "Inactive"]),
        "CommitmentDiscountType": random.choice(["RI", "Savings Plan"]),
        "ConsumedQuantity": fake.pydecimal(left_digits=4, right_digits=2, positive=True),
        "ConsumedUnit": random.choice(["Hours", "GB", "Requests"]),
        "ContractedCost": fake.pydecimal(left_digits=5, right_digits=2, positive=True),
        "ContractedUnitPrice": fake.pydecimal(left_digits=3, right_digits=2, positive=True),
        "EffectiveCost": fake.pydecimal(left_digits=5, right_digits=2, positive=True),
        "InvoiceIssuerName": fake.company(),
        "ListCost": fake.pydecimal(left_digits=5, right_digits=2, positive=True),
        "ListUnitPrice": fake.pydecimal(left_digits=3, right_digits=2, positive=True),
        "PricingCategory": random.choice(["On-Demand", "Reserved"]),
        "PricingQuantity": fake.pydecimal(left_digits=2, right_digits=0, positive=True),
        "PricingUnit": random.choice(["Hours", "GB", "Requests"]),
        "ProviderName": "Microsoft",
        "PublisherName": "Microsoft",
        "RegionId": fake.random_int(min=1, max=100),
        "RegionName": fake.city(),
        "ResourceId": fake.uuid4(),
        "ResourceName": fake.word(),
        "ResourceType": random.choice(["Virtual Machine", "Storage Account", "Network Interface"]),
        "ServiceCategory": random.choice(["Compute", "Storage", "Networking"]),
        "ServiceName": fake.word(),
        "SkuId": fake.uuid4(),
        "SkuPriceId": fake.uuid4(),
        "SubAccountId": fake.uuid4(),
        "SubAccountName": fake.company(),
        "SubAccountType": random.choice(["Production", "Development"]),
        "Tags": fake.pydict(nb_elements=5, value_types=[str]),
        "x_AccountId": fake.uuid4(),
        "x_AccountName": fake.company(),
        "x_AccountOwnerId": fake.uuid4(),
        "x_BilledCostInUsd": fake.pydecimal(left_digits=5, right_digits=2, positive=True),
        "x_BilledUnitPrice": fake.pydecimal(left_digits=3, right_digits=2, positive=True),
        "x_BillingAccountId": fake.uuid4(),
        "x_BillingAccountName": fake.company(),
        "x_BillingExchangeRate": fake.pydecimal(left_digits=3, right_digits=4, positive=True),
        "x_BillingExchangeRateDate": fake.date_between(start_date="-1y", end_date="today"),
        "x_BillingProfileId": fake.uuid4(),
        "x_BillingProfileName": fake.word(),
        "x_ContractedCostInUsd": fake.pydecimal(left_digits=5, right_digits=2, positive=True),
        "x_CostAllocationRuleName": fake.word(),
        "x_CostCenter": fake.word(),
        "x_CustomerId": fake.uuid4(),
        "x_CustomerName": fake.company(),
        "x_EffectiveCostInUsd": fake.pydecimal(left_digits=5, right_digits=2, positive=True),
        "x_EffectiveUnitPrice": fake.pydecimal(left_digits=3, right_digits=2, positive=True),
        "x_InvoiceId": fake.uuid4(),
        "x_InvoiceIssuerId": fake.uuid4(),
        "x_InvoiceSectionId": fake.uuid4(),
        "x_InvoiceSectionName": fake.word(),
        "x_ListCostInUsd": fake.pydecimal(left_digits=5, right_digits=2, positive=True),
        "x_PartnerCreditApplied": fake.pydecimal(left_digits=4, right_digits=2, positive=True),
        "x_PartnerCreditRate": fake.pydecimal(left_digits=2, right_digits=2, positive=True),
        "x_PricingBlockSize": fake.pydecimal(left_digits=2, right_digits=0, positive=True),
        "x_PricingCurrency": "USD",
        "x_PricingSubcategory": fake.word(),
        "x_PricingUnitDescription": fake.sentence(nb_words=6),
        "x_PublisherCategory": fake.word(),
        "x_PublisherId": fake.uuid4(),
        "x_ResellerId": fake.uuid4(),
        "x_ResellerName": fake.company(),
        "x_ResourceGroupName": fake.word(),
        "x_ResourceType": random.choice(["Virtual Machine", "Storage Account", "Network Interface"]),
        "x_ServicePeriodEnd": fake.date_between(start_date="-1y", end_date="today"),
        "x_ServicePeriodStart": fake.date_between(start_date="-2y", end_date="-1y"),
        "x_SkuDescription": fake.sentence(nb_words=6),
        "x_SkuDetails": fake.pydict(nb_elements=5, value_types=[str]),
        "x_SkuIsCreditEligible": fake.boolean(),
        "x_SkuMeterCategory": fake.word(),
        "x_SkuMeterId": fake.uuid4(),
        "x_SkuMeterName": fake.word(),
        "x_SkuMeterSubcategory": fake.word(),
        "x_SkuOfferId": fake.uuid4(),
        "x_SkuOrderId": fake.uuid4(),
        "x_SkuOrderName": fake.word(),
        "x_SkuPartNumber": fake.random_int(min=1000, max=9999),
        "x_SkuRegion": fake.city(),
        "x_SkuServiceFamily": fake.word(),
        "x_SkuTerm": random.choice(["1 Year", "3 Years"]),
        "x_SkuTier": random.choice(["Standard", "Premium"]),
    }
    data.append(row)

# Create a pandas DataFrame from the data
df = pd.DataFrame(data)

# Save the DataFrame to a CSV file
df.to_csv("azure_cost_and_usage_data.csv", index=False)